### ISSUE TITLE
./train-local: line 34: jq: command not found

### ISSUE THREAD

**Issue by chenjw851009** [idealo/image-quality-assessment#14]
when I use cpu to train a model, there are something wrong like this:

localhost:image-quality-assessment-master chenjingwei$ ./train-local \
> --docker-image nima-cpu \
> --config-file $(pwd)/models/MobileNet/config_mobilenet_technical.json \
> --samples-file $(pwd)/data/TID2013/tid_labels_train.json \
> --image-dir $(pwd)/data/test
./train-local: line 34: jq: command not found
"docker run" requires at least 1 argument.
See 'docker run --help'.

how to solve this ?thanks!

**Comment by clennan** [comment]
Hi, it seems you do not have the command line JSON processor `jq` installed on your system. See here on how to download and install it https://stedolan.github.io/jq/download/

I will add it to the requirements

**Comment by chenjw851009** [comment]
hi, there are some parameters in the file"config_mobilenet_technical" , one of them is "docker_image": "idealo/nima-cpu", but when I use cpu to train the model, may I modify it to Nima-cpu?

{
  "train_env": "TID2013",
  "s3_bucket": "ds-hotel-image-assessment",
  "docker_image": "idealo/nima-gpu",
  "base_model_name": "MobileNet",
  "existing_weights": null,
  "n_classes": 10,
  "batch_size": 64,
  "epochs_train_dense": 25,
  "learning_rate_dense": 0.001,
  "decay_dense": 0,
  "epochs_train_all": 25,
  "learning_rate_all": 0.0000003,
  "decay_all": 0,
  "dropout_rate": 0.75,
  "multiprocessing_data_load": true,
  "num_workers_data_load": 8,
  "img_format": "bmp"
}

**Comment by clennan** [comment]
yes, you have to change it when you want to train on cpu. Change it to the name of your local nima cpu docker image, it seems to be called `Nima-cpu` in your case

**Comment by chenjw851009** [comment]
hi one more question ,when I modify the parameter to  Nima-cpu ,the log is blow.

localhost:image-quality-assessment-master chenjingwei$ ./train-local \
> --config-file $(pwd)/models/MobileNet/config_mobilenet_technical.json \
> --samples-file $(pwd)/data/TID2013/tid_labels_train.json \
> --image-dir $(pwd)/data/test
Unable to find image 'idealo/nima-cpu:latest' locally
docker: Error response from daemon: pull access denied for idealo/nima-cpu, repository does not exist or may require 'docker login'.
See 'docker run --help'.

I have build the Nima-cpu and the docker is login
do you know how to solve it, thanks!

**Comment by clennan** [comment]
are you sure that your `docker_image` parameter is set to `Nima-cpu` in your config? Because the script `train-local` is trying to access the docker image `idealo/nima-cpu` on DockerHub, which does not exist. 

When you are in `src` directory, run
```
docker build -t Nima-cpu . -f Dockerfile.cpu
```

Then change your config to 
```
{
 ...
  "docker_image": "Nima-cpu",
 ...
}
```

**Comment by chenjw851009** [comment]
thanks very much! I solve this issue by your provided method in my Mac OS, but when I run this on service machine(linux - ubuntu os) ,some errors report again:


Epoch 1/25
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/src/handlers/data_generator.py", line 29, in __getitem__
    X, y = self.__data_generator(batch_samples)
  File "/src/handlers/data_generator.py", line 45, in __data_generator
    img = utils.load_image(img_file, self.img_load_dims)
  File "/src/utils/utils.py", line 39, in load_image
    return np.asarray(keras.preprocessing.image.load_img(img_file, target_size=target_size))
  File "/usr/local/lib/python3.5/dist-packages/keras/preprocessing/image.py", line 387, in load_img
    img = pil_image.open(path)
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/src/images/I04_11_1.bmp'
"""

but I set the file path to "/data/test" not "/src/images" , and I run it on cpu, do you know the reason?

thanks

**Comment by chenjw851009** [comment]
yes,sir!
i have copied the images to the filepath "data/test" in the service machine


--------------原始邮件--------------
发件人："Christopher Lennan "<notifications@github.com>;
发送时间：2018年11月28日(星期三) 晚上9:29
收件人："idealo/image-quality-assessment" <image-quality-assessment@noreply.github.com>;
抄送："chenjw851009 "<chenjw@tangdou.com>;"Author "<author@noreply.github.com>;
主题：Re: [idealo/image-quality-assessment] ./train-local: line 34: jq: command not found (#14)
-----------------------------------

 
The /src/images directory is the image directory in the Docker container, which the local image directory is mounted to, in your case data/test.
 
Have you copied the images to the service machine to data/test?

**Comment by chenjw851009** [comment]
I  got it!
the image"I04_11_1.bmp"do exist in the directory"data/test", but it's format is not ".bmp"but ".BMP",so it can not find this image.
          
  thanks again, have a good time!!!
