### ISSUE TITLE
"maxentropy.skmaxent"  in the file get_labels.py

### ISSUE THREAD

**Issue by chenjw851009** [idealo/image-quality-assessment#15]
hi, I meet one more question.
there are one line code "from maxentropy.skmaxent import MinDivergenceModel"  in the file get_labels.py, but  I can not find some relations file or code about "maxentropy".

**Comment by MrBanhBao** [comment]
That is because maxentropy is a external module we use.
Just pip install the module, then you should find a reference to the code of this module.
https://pypi.org/project/maxentropy/
