### ISSUE TITLE
IndexError: list index out of range----when I run predict.py

### ISSUE THREAD

**Issue by chenjw851009** [idealo/image-quality-assessment#17]
hi when I run the source file "predict.py", an error report:

 File "predict.py", line 55, in main
    sample[i] = calc_mean_score(predictions[i])#'mean_score_prediction'
IndexError: list index out of range

my parameter setting blow:
localhost:src chenjingwei$ python predict.py \
> --base-model-name MobileNet \
> --weights-file ../models/MobileNet/weights_mobilenet_aesthetic_0.07.hdf5 \
> --image-source tests/test_images

and the source code is:
  # calc mean scores and add to samples
    for i, sample in enumerate(samples):
        sample[i] = calc_mean_score(predictions[i])#'mean_score_prediction'
is anything wrong?

thanks.

**Comment by clennan** [comment]
Please check out issue #4, this might help to run predict.py without Docker.

**Comment by chenjw851009** [comment]
hi  I follow your instructions, the issue always exist.

the source code:
for i, sample in enumerate(samples):
    sample['mean_score_prediction'] = calc_mean_score(predictions[i])

it report : IndexError: list index out of range
seems the problem is about the parameter predictions[I], because when I debug , the predictions is null.
in addition, what is your version of tensorflow and Keras ?
thanks

**Comment by chenjw851009** [comment]
hi, I have solved this problem. but the error still exist with your instructions, I don't know the reason.
however, I train the new model with other image dataset, then use the model to predict the images, and it run successfully.
besides, the source code in the line 47 of the file predict.py: I modify the para "64".

   data_generator = TestDataGenerator(samples, image_dir, 64, 10, nima.preprocessing_function(),
                                       img_format=img_format)

this is what I do, thanks very much.
