### ISSUE TITLE
label generation

### ISSUE THREAD

**Issue by flighted** [idealo/image-quality-assessment#20]
Hi ,I am confused about the label generation , if you could help, I would appreciate it. When I open the get_labels.py script, I don't know the parameter 'source-file-mean' . How can I generate labels  about my data?  And what  ten numbers of  label  mean ?

**Comment by anon-techie** [comment]
Hi, source-file-mean is the text file with image files names and its corresponding mean scores. It's the "mos_with_names.txt" file included in TID2013 dataset. I can't recall what it's called in AVA dataset. For instance, let's assume you have a dataset of 1000 images, you need a text file with image filenames and its corresponding mean scores. The labels generated using get_label.py script is the 10 numbers frequency of the mean score of each image. E.g. 231893.bmp image has a mean score of 22.3, you might get a random 10 digit frequency averaging to 22.3. Hence something like - 
{
    "image_id": "231893",
    "label": [2,8,19,36,76,52,16,9,3,2]
  }
You are welcome!

**Comment by flighted** [comment]
Hi，I  appreciate your response. But  I'm confused about mean scores . I want to ask whether it means  the average of the whole picture .

**Comment by anon-techie** [comment]
The score given to an image in the dataset based on aesthetics(AVA) or technical specs(TID2013) is considered mean score.

**Comment by flighted** [comment]
Hi，I know that, but if I want to make my own dataset according to TID2013,  how do I get the mean score before  using get_label.py script. I want to ask whether the mean score is predicted by the model  and then use get_label.py  to get a random 10 digit frequency averaging to mean scores. I found the mean scores of TID2013 data  generated by people's observations.

**Comment by anon-techie** [comment]
I'm not sure about the methodology used to score images in AVA and TID2013 dataset. Maybe you can find some clues here: https://github.com/hcl14/AVA-and-TID2013-image-quality-assessment 
For my case study, I took few thousand random images and made my associates give scores based on aesthetics.

**Comment by clennan** [comment]
Hi, the mean score is the mean of all scores given to a certain image. It is not a model prediction. If you want to create your own TID2013 check their paper http://www.ponomarenko.info/papers/tid2013.pdf
