### ISSUE TITLE
Predict script number of images limit

### ISSUE THREAD

**Issue by anon-techie** [idealo/image-quality-assessment#21]
Hi, is there a limit to how many images predict script can generate ratings for? I have a dataset of couple of thousand images and the predict script run on 800 or so images. It doesn't load anything beyond that number. I checked my resource utilization, its even using 10% of the memory. Is there any way I can increase this limit to cover the whole dataset?

Thanks!

**Comment by clennan** [comment]
Hi, no, there is no limit. The data generator in `src/evaluater/predict.py` creates batches of 64 images and should iterate through your dataset.

Do you get an error or it just finishes after 800 images?
