### ISSUE TITLE
Example code to load pretrained model in keras

### ISSUE THREAD

**Issue by dbuytaer** [idealo/image-quality-assessment#22]
Hi,

Would it be possible to provide an example code to load the pretrained models and weights (the config json and weights hdf5 files inside the MobileNet folder) into a model using keras, and how to apply it to predict a score for an input image please?

I haven't used keras before, but i did some searching to load the models and tried "model_from_json". However, this gave the error "Improper config format" (see ipython notebook attached).

I tried the Docker image first, compiling worked, but the prediction failed in the docker quickstart terminal and gave the following error:  "module 'tensorflow' has no attribute 'get_default_graph'"

thanks in advance for your help!

Kind regards, 

Dimitri

[idealo_test.zip](https://github.com/idealo/image-quality-assessment/files/2952686/idealo_test.zip)

**Comment by chumengdd** [comment]
i met same problem, i solved it by changing the lower version tensorflow(1.8.0),

**Comment by clennan** [comment]
Hi Dimitri,

not a 100% sure what you are after, but check out this code example I gave in a previous issue https://github.com/idealo/image-quality-assessment/issues/1#issuecomment-416191140
