### ISSUE TITLE
Activate citations

### ISSUE THREAD

**Issue by juanabascal** [idealo/image-quality-assessment#25]
Hi, I'm an undergraduate student from University Carlos III of Madrid and I am using your code, specially your trained weights for MobileNet, for doing my final project. I would like to be able to cite your GitHub repository correctly. Here is a guide that allow to create a DOI for your repository https://help.github.com/en/articles/referencing-and-citing-content.

I don't know if this would be possible but it would be nice to put a good citation in my project.

Thanks in advance.

**Comment by clennan** [comment]
Hi, I have added citation details to the README 
https://github.com/idealo/image-quality-assessment#cite-this-work

Good luck with your final project :)
