### ISSUE TITLE
how to convert to .mlmodel file

### ISSUE THREAD

**Issue by godmanzheng** [idealo/image-quality-assessment#27]
I'd like to convert to hdf5 model to IOS .mlmodel ,seems that it work, but the result given from the .mlmodel is not correct, I suspect it's the resson I didn't get preprocessing parameter right,so can somebody give some advice what parameter should I give to the call:
apple_model = coremltools.converters.keras.convert(nima.nima_model,input_names=['image'],image_input_names='image')

**Comment by clennan** [comment]
Hi, did you preprocess the images with `nima.preprocessing_function()` before using your apple_model for predictions?

**Comment by godmanzheng** [comment]
I was trying to convert the weights_mobilenet_technical_0.11.hdf5 file from package, I'm not very sure whether nima.preprocessing_function() has been called (it seems so to me)，when converting, I just load the model with code like this:

nima = Nima('MobileNet', weights=None)
nima.build()
nima.nima_model.load_weights('./technical.hdf5')

and no further process

**Comment by godmanzheng** [comment]
when I use thr mlmodel in IOS project, I don't know what the nima.preprocessing_function() has done to the image, is there any suggestion how I can process the image?

**Comment by clennan** [comment]
You need to apply Imagenet transformations in tf mode https://github.com/keras-team/keras-applications/blob/dda499735da01ab6c6f029b37dbdf35cc82db136/keras_applications/imagenet_utils.py#L21

Not sure how best to apply them in your iOS project but pretty sure this can be done in Swift
