### ISSUE TITLE
Unable to find image 'nima-cpu:latest' locally

### ISSUE THREAD

**Issue by ahbon123** [idealo/image-quality-assessment#31]
I try to score a demo picture but get an error:

`./predict  --docker-image nima-cpu --base-model-name MobileNet --weights-file $(pwd)/models/MobileNet/weights_mobilenet_technical_0.11.hdf5 --image-source $(pwd)/src/tests/test_images/42039.jpg`

Does someone know how to deal with this issue? Thanks.

```
Unable to find image 'nima-cpu:latest' locally
docker: Error response from daemon: pull access denied for nima-cpu, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

**Comment by clennan** [comment]
Hi, you have to build the Docker image `nima-cpu` first with `docker build -t nima-cpu . -f Dockerfile.cpu`

See also https://github.com/idealo/image-quality-assessment#getting-started

**Comment by ahbon123** [comment]
Thanks. If want use GPU, then I should build Docker image `nima-cpu` with `docker build -t nima-gpu . -f Dockerfile.gpu`, right?

**Comment by clennan** [comment]
Yes, the docker image is then called `nima-gpu` and not `nima-cpu`

**Comment by ahbon123** [comment]
Ok, I get it thanks. If necessary, I would suggest you could also add guide for training model locally on GPU.

**Comment by clennan** [comment]
Closing this now, let‘s discuss GPU predictions in #32
