### ISSUE TITLE
Error with Deepbinner:  ImportError: libcuda.so.1: cannot open shared object file: No such   file or directory   Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by gmercadov** [idealo/image-quality-assessment#33]
Hello.
I'm trying to use deepbinner for demultiplexing by native barcodes the data of several patients I've obtaining through MinION sequencing. I've obtained this error and I don't understand what could happen. Any help? Thank you.

`(Deepbinner) [ugm@et8 Lecturas_30_05_2019]$ deepbinner classify  
--native fast5_pass/ > classifications
Using TensorFlow backend.
Traceback (most recent call last):
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in  
<module>
     from tensorflow.python.pywrap_tensorflow_internal import *
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in  
<module>
     _pywrap_tensorflow_internal = swig_import_helper()
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in  
swig_import_helper
     _mod = imp.load_module('_pywrap_tensorflow_internal', fp,  
pathname, description)
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/imp.py",  
line 243, in load_module
     return load_dynamic(name, filename, file)
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/imp.py",  
line 343, in load_dynamic
     return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such  
file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
   File "/programas/anaconda/3-4.4.0/envs/Deepbinner/bin/deepbinner",  
line 10, in <module>
     sys.exit(main())
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/deepbinner/deepbinner.py", line 59, in  
main
     from .classify import classify
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/deepbinner/classify.py", line 24, in  
<module>
     from keras.models import load_model
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/keras/__init__.py", line 3, in  
<module>
     from . import utils
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in  
<module>
     from . import conv_utils
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in  
<module>
     from .. import backend as K
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in  
<module>
     from .tensorflow_backend import *
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in  
<module>
     import tensorflow as tf
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in  
<module>
     from tensorflow.python import pywrap_tensorflow  # pylint:  
disable=unused-import
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in  
<module>
     from tensorflow.python import pywrap_tensorflow
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in  
<module>
     raise ImportError(msg)
ImportError: Traceback (most recent call last):
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in  
<module>
     from tensorflow.python.pywrap_tensorflow_internal import *
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in  
<module>
     _pywrap_tensorflow_internal = swig_import_helper()
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in  
swig_import_helper
     _mod = imp.load_module('_pywrap_tensorflow_internal', fp,  
pathname, description)
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/imp.py",  
line 243, in load_module
     return load_dynamic(name, filename, file)
   File  
"/programas/anaconda/3-4.4.0/envs/Deepbinner/lib/python3.6/imp.py",  
line 343, in load_dynamic
     return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such  
file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**Comment by clennan** [comment]
You should post your Deepbinner issues on the Deepbinner repo, this repo has nothing to do with it.
