### ISSUE TITLE
Support for tensorboard

### ISSUE THREAD

**Issue by SophieMBerger** [idealo/image-quality-assessment#35]
As someone that is not too experienced with Tensorflow and ML, it would be awesome if you could include support for TensorBoard with the repo.

**Comment by MrBanhBao** [comment]
@SophieMBerger there is actually a TensorBoard Callback passed during the training process [have a look here](https://github.com/idealo/image-quality-assessment/blob/32d20ae161ad591715e8167fc4190ec2fdb186a4/src/trainer/train.py#L83).

You can have a look on the graph and the training logs with following terminal command:
`tensorboard --logdir=<path to log dir>`
