### ISSUE TITLE
Dataset with average score only

### ISSUE THREAD

**Issue by midm** [idealo/image-quality-assessment#36]
Hi !
First of all I'd like to point out the fact the I'm a beginner in ML so please excuse me if my question does not make sense or if the vocabulary used is not appropriate.

I would like to train the aesthetic model on my own dataset to have better results. I don't have labels with several scores given from 1 to 10 but a single score (a percentage from 0 to 100) for each photo. Is there a way to use it anyway ? If yes, do you have any tips on how to achieve this ?

Thanks !

**Comment by clennan** [comment]
Hi, yes, you could try to bin your percentage scores into buckets of 1 to 10. This should work with Nima and its EMD IOS’s function.

Alternatively you could train a regression model with MSE loss which predicts the percentage score. For this you would have to build your own model and can’t use Nima.
