### ISSUE TITLE
Test in other image type

### ISSUE THREAD

**Issue by yuyifan1991** [idealo/image-quality-assessment#38]
Hi, I have changed the image type from jpg to bmp that in the position of /src/evaluate/predict, But it can only test the jpg image type. How can I do it that can test the bmp images?

**Comment by datitran** [comment]
Convert bmp to jpg?

**Comment by yuyifan1991** [comment]
yes

**Comment by yuyifan1991** [comment]
@datitran Thanks so much. I have solve the problem because of my carelessness.  I should remake the code after modifying it. But another problem occurred, I just run the commend : docker build -t nima-cpu . -f Dockerfile.cpu to update the code, But in fact, it will carry out other steps which is not in need. So which commend  should I run?

**Comment by clennan** [comment]
Hi, currently prediction only works on jpg images. So the easiest would be to convert your bmp images to jpg first. Then the original code should work and you can follow the steps in `README.md`

**Comment by yuyifan1991** [comment]
@clennan，Thank you so much. But in fact, I can predict the works on bmp images by modifying the code. The problem now for me is the  compiling, it costs too much time by tun the commend : docker build -t nima-cpu . -f Dockerfile.cpu. Is there more easier commend? By the way, is it necessary to make owe datasets for training?

**Comment by yuyifan1991** [comment]
@clennan，Thank you so much. But in fact, I can predict the works on bmp images by modifying the code. The problem now for me is the  compiling, it costs too much time by run the commend : docker build -t nima-cpu . -f Dockerfile.cpu. Is there more easier commend? By the way, is it necessary to make owe datasets for training?

**Comment by clennan** [comment]
See #4 for details on how to run predictions outside of docker. 

You don't have to make your own dataset, we have used public datasets for training the aesthetic and technical model, see here https://github.com/idealo/image-quality-assessment#datasets

If you want to use these models in a certain domain (e.g. hotel image aesthetics) I would recommend to build your own dataset and fine tune the models on those.

**Comment by yuyifan1991** [comment]
@clennan, Thank you so much. And now, I want to Train locally on CPU, I loaded the TID2013 dataset and put it in the correct position. But when I run the commend : ./train-local \
--config-file $(pwd)/models/MobileNet/config_mobilenet_technical.json \
--samples-file $(pwd)/data/TID2013/tid_labels_train.json \
--image-dir /path/to/image/dir/local
faults occurred : ./train-local: line 34: jq: command not found
I really don't know how to solve it.

**Comment by clennan** [comment]
See here on how to install ‘jq’ https://github.com/idealo/image-quality-assessment/issues/14#issuecomment-441974449

I will add it to the ‘README.md’

**Comment by yuyifan1991** [comment]
@clennan,Thank you so much. If I want to train the data on Linux Server, How should I do?

**Comment by bhavesh907** [comment]
> See #4 for details on how to run predictions outside of docker.
> 
> You don't have to make your own dataset, we have used public datasets for training the aesthetic and technical model, see here https://github.com/idealo/image-quality-assessment#datasets
> 
> If you want to use these models in a certain domain (e.g. hotel image aesthetics) I would recommend to build your own dataset and fine tune the models on those.

I tried to fine tune it but I'm always getting values between 3.5 and 5. any suggestion how to fix that?

**Comment by clennan** [comment]
@bhavesh907 see #50
