### ISSUE TITLE
how to calculate LCC and SRCC

### ISSUE THREAD

**Issue by chenneng** [idealo/image-quality-assessment#40]

**Comment by clennan** [comment]
SRCC is the Spearman Rank Correlation Coefficent, see here https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.spearmanr.html

LCC is the normal Linear Correlation Coefficient, see here https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.pearsonr.html
