### ISSUE TITLE
Got an error when training on CPU

### ISSUE THREAD

**Issue by volunteers** [idealo/image-quality-assessment#41]
I use this for training:
`./train-local --config-file $(pwd)/models/MobileNet/config_mobilenet_technical.json --samples-file $(pwd)/data/TID2013/tid_labels_train.json --image-dir ~/Downloads/image-quality-assessment-master/training_data/distorted_images/
`

Got error message like:
> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/src/trainer/train.py", line 6, in <module>
>     from sklearn.model_selection import train_test_split
> **ModuleNotFoundError: No module named 'sklearn'**

I am pretty sure sklearn installed and I can even run 
`>> from sklearn.model_selection import train_test_split`  in python directly.
I tried both on MacOS and Ubuntu, got the same error.

**Comment by skiry** [comment]
Try to put `scikit-learn` in the `requirements.txt` file from the src directory before building the docker.

**Comment by volunteers** [comment]
put scikit-learn in the requirements.txt solved the problem.
