### ISSUE TITLE
Can I use this model to evaluate GAN model outputs?

### ISSUE THREAD

**Issue by FantasyJXF** [idealo/image-quality-assessment#43]
Since the GAN model was not so stable now, usually we might get terrible generated images, just like the following ones.

![20190910120007](https://user-images.githubusercontent.com/16235526/64583165-91846580-d3c2-11e9-8a9e-b64d4b278631.jpg)

My question is whether we can evaluate these images with NIMA with my own dataset, and it's so hard to create my own AVA dataset.

**Comment by clennan** [comment]
Hi, pretty sure that the aesthetic model trained on AVA won't give you useful results on your GAN generated images.
