### ISSUE TITLE
Could you convert hdf5 to pd?

### ISSUE THREAD

**Issue by onexuan** [idealo/image-quality-assessment#45]
Could you convert hdf5 to pd?

**Comment by clennan** [comment]
@onexuan What is pd?

**Comment by onexuan** [comment]
tensorflow model file, or how to convert it to onnx file

**Comment by clennan** [comment]
I provided some code on how to convert .hdf5 to .pb models here https://github.com/idealo/image-quality-assessment/issues/7#issuecomment-437293398
