### ISSUE TITLE
what's the aesthetic and technical  model's difference?

### ISSUE THREAD

**Issue by jt120** [idealo/image-quality-assessment#5]
hi, idealo

I read your code, also the paper, but I'm not found the difference between aesthetic model and technical model. also the aesthetic model seem good on metric.

So do you know the difference?

tks

**Comment by clennan** [comment]
Hi, the difference is that the aesthetic model was trained on the AVA dataset, and the technical model on the TID2013 dataset. Both models have the same architecture, they were just trained on different datasets. You can find further details and links to the datasets in the [README](https://github.com/idealo/image-quality-assessment#datasets)

**Comment by leeqiaogithub** [comment]
@clennan I have read data/TID2013/get_labels.py,but i am confused of line 5 ----'from maxentropy.skmaxent import MinDivergenceModel'. I did not google of module 'maxentropy',could you please tell me what it is ?
