### ISSUE TITLE
Accuracy of results seems odd.

### ISSUE THREAD

**Issue by repollo** [idealo/image-quality-assessment#50]
For some reason I'm getting odd values, and I'm not sure if its me or the model. Take a look and let me know what you think...

<img width="1127" alt="Screen Shot 2019-10-16 at 3 47 25 PM" src="https://user-images.githubusercontent.com/2671466/66953328-4ba76680-f02c-11e9-94f2-41831a4f4532.png">

I was expecting to get around 9.8+ score on the 1.jpg, the one with the tree and blue sky. Is from the NIMA paper.

Additionally what scores or results are you guys getting? Maybe is just something on my end...

**Comment by clennan** [comment]
I guess you are using the aesthetic model..it was trained on the AVA dataset which has the vast majority of mean scores in the range 4 to 7 (see Figure 1 in the NIMA paper). So the model will also only predict in that range. People we generally scored quite high in AVA I believe which also shows in your predictions.

We labelled a hotel dataset ourselves and had a wider range of mean scores which then also resulted in the fine-tuned classifier to predict more extreme scores.
