### ISSUE TITLE
Illegal Instruction when running ./predict

### ISSUE THREAD

**Issue by tuancorn97** [idealo/image-quality-assessment#55]
Hi there,
 I have just downloaded your models and installed all the requirement, but it did not work when I tried predicting the images with
`./predict  \
--docker-image nima-cpu \
--base-model-name MobileNet \
--weights-file $(pwd)/models/MobileNet/weights_mobilenet_technical_0.11.hdf5 \
--image-source $(pwd)/src/tests/test_images/42039.jpg
`

It then showed an error of Illegal Instruction in the file entrypoint.predict.cpu.sh:
`entrypoints/entrypoint.predict.cpu.sh: line 12:     6 Illegal instruction     (core dumped) python -m evaluater.predict --base-model-name $BASE_MODEL_NAME --weights-file $WEIGHTS_FILE --image-source $IMAGE_SOURCE
`

**Comment by clennan** [comment]
Hm, not sure what is happening there. We upgraded to TF2.0 today, can you try again with the newest version and see if it works?

**Comment by RonSv** [comment]
Hello. Same problem. With newest version also.

**Comment by clennan** [comment]
Which operating system and Docker version are you running?

**Comment by RonSv** [comment]
Operating System: Arch Linux
Kernel Version: 4.19.81-1-lts
Docker 19.03.4-ce

**docker version**
```cli
Client:
 Version:           19.03.4-ce
 API version:       1.40
 Go version:        go1.13.1
 Git commit:        9013bf583a
 Built:             Sat Oct 19 04:40:07 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.4-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.1
  Git commit:       9013bf583a
  Built:            Sat Oct 19 04:39:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.0.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
**docker info**
```cli
Server Version: 19.03.4-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc version: d736ef14f0288d6993a1845745d6756cfc9ddd5a
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.81-1-lts
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 Docker Root Dir: /var/lib/docker
 Debug Mode: false 
```

**Comment by RonSv** [comment]
Probably the reason is cpu. (Intel Xeon X5675) https://github.com/tensorflow/serving/issues/1342

**Comment by RonSv** [comment]
I solve it building tensorflow binary without avx instruction. There are compiled WHL for different processors - https://github.com/yaroslavvb/tensorflow-community-wheels/issues

Then add in dockerfile
```
COPY tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl /tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl

RUN pip uninstall tensorflow -y \
    && pip install tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl \
    && rm -rf /tensorflow-2.0.0-cp36-cp36m-linux_x86_64.whl
```

**Comment by Sps113** [comment]
get from here https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-2.0.0-cp36-cp36m-manylinux2010_x86_64.whl
