### ISSUE TITLE
Jenkins Deployment

### ISSUE THREAD

**Issue by gitadministrator011** [idealo/image-quality-assessment#57]
Please help on this issue:

You must specify a region. You can also configure your region by running "aws configure".
You must specify a region. You can also configure your region by running "aws configure".
/tmp/jenkins6556285910827171418.sh: line 25: jq: command not found
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
entered existing service
/tmp/jenkins6556285910827171418.sh: line 31: jq: command not found
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
/tmp/jenkins6556285910827171418.sh: line 32: [: =: unary operator expected
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

**Comment by clennan** [comment]
Please provide more details, what command were you running, what system are you working on. The error messages are quite descriptive, have you addressed those?

**Comment by gitadministrator011** [comment]
> Please provide more details, what command were you running, what system are you working on. The error messages are quite descriptive, have you addressed those?

what you can see in the downloaded files are the same that i used.

**Comment by clennan** [comment]
I can't see any downloaded files. You are also not answering my previous questions.
