### ISSUE TITLE
could you please let me know where to get config and samples.json for local train

### ISSUE THREAD

**Issue by djangid** [idealo/image-quality-assessment#63]
could you please let me know where to get config and samples.json for local train

**Comment by clennan** [comment]
Hi, 

the aesthetic config and samples files for training are
https://github.com/idealo/image-quality-assessment/blob/master/models/MobileNet/config_aesthetic_cpu.json
https://github.com/idealo/image-quality-assessment/blob/master/data/AVA/ava_labels_train.json


The technical files are 
https://github.com/idealo/image-quality-assessment/blob/master/models/MobileNet/config_technical_cpu.json
https://github.com/idealo/image-quality-assessment/blob/master/data/TID2013/tid_labels_train.json
