### ISSUE TITLE
need info to build config and samples json

### ISSUE THREAD

**Issue by djangid** [idealo/image-quality-assessment#64]
can anyone explain "train_env": "TID2013",
  "s3_bucket": "ds-hotel-image-assessment",
  "docker_image": "idealo/nima-gpu",
  "base_model_name": "MobileNet",
  "existing_weights": null,
  "n_classes": 10,
  "batch_size": 64,
  "epochs_train_dense": 25,
  "learning_rate_dense": 0.001,
  "decay_dense": 0,
  "epochs_train_all": 25,
  "learning_rate_all": 0.0000003,
  "decay_all": 0,
  "dropout_rate": 0.75,
  "multiprocessing_data_load": true,
  "num_workers_data_load": 8,
  "img_format": "bmp"

**Comment by clennan** [comment]
This config file lists all the parameters needed to train the technical model on AWS. Let us know if you have more specific questions on any of the parameters

**Comment by djangid** [comment]
could you please let me know how to know what field is what and more information so i can understand how to make my own filed i nfromtion

**Comment by clennan** [comment]
Hi, most field names are quite descriptive and should be clear if you deal with neural nets. If you have specific questions to a field please reopen this issue, but I am not going to run through all of them, closing this for now
