### ISSUE TITLE
some questions and advices

### ISSUE THREAD

**Issue by MaltoseMai** [idealo/image-quality-assessment#65]
Impressed with you guys awesome job!

Here are some questions and advices:
1. How low EMD means the model is really good for prediction?
2. What's the accurate rate when validating on the test dataset?
3. Have you guys trained with MobileNetv2, even MobileNetv3? or any plan?

**Comment by clennan** [comment]
Hi,

ad 1.) difficult to say, we actually looked at rank correlations a lot to evaluate performance, see this discussion for further details https://github.com/idealo/image-quality-assessment/issues/18#issuecomment-451095387

ad 2.) not sure what you mean..what rate are you talking about?

ad 3.) no, we haven't and we don't have plans on doing it. See here for the results with MobileNetV2 someone reported last year https://github.com/idealo/image-quality-assessment/issues/18#issuecomment-449927721
