### ISSUE TITLE
Could you share the weights files you attained based on VGG16 and Inception-V2

### ISSUE THREAD

**Issue by tongqingzhou-nudt** [idealo/image-quality-assessment#69]
I am trying to fine-tuning the assessment model for other specific scenarios.  Retraining from the initial weights would no doubt cost too much time. I am aware that you have posted the weights of Mobilenet model. I wonder if you can share the weights files you attained for VGG16 and Inception-V2.
Thanks a lot.

**Comment by clennan** [comment]
Hi, I can’t, I think I trained based on Vgg16 and some Inception model, but have not saved these weights, sorry
