### ISSUE TITLE
Why do pure, colored frames rank very high? E.g. a pure black frame scores 5.8 aesthetical

### ISSUE THREAD

**Issue by suissemaxx** [idealo/image-quality-assessment#76]
First of all: Thanks very much to you and your team for making code and models available. Very cool and helpful! 👍

I noticed that pure color frames (like total black, white, grey, reds etc.) rank astonishingly high. 

E.g. a simple, empty black frame gets a technical score of 5.8 and and an aesthetical score of 4.x. Why is that and shouldn't these frames score much lower?

Thanks in advance for any insight on that!

**Comment by clennan** [comment]
Hi, my guess would be that the training dataset did not include pure color frames and as such the model never learned how these images perform aesthetically

**Comment by suissemaxx** [comment]
Makes senses. Thanks!
