### ISSUE TITLE
GPU training results in docker error

### ISSUE THREAD

**Issue by wmelton** [idealo/image-quality-assessment#8]
When running ./train-ec2 with a verified running EC2 GPU instance, the DOCKER_REMOTE_RUN command fails with this error: 

`nvidia-docker: command not found`

Here is the full log - 

```Login Succeeded
Using default tag: latest
latest: Pulling from idealo/nima-gpu
Digest: sha256:8503017ed9427fa63d321911e620c01bb897d9bfd5494be4af1ea8b3e6d9bb7f
Status: Image is up to date for idealo/nima-gpu:latest
gpu-aesthetic-config.json                                                                              100%  480    11.5KB/s   00:00
labels_train.json                                                                                      100%  392KB   1.3MB/s   00:00
sudo: nvidia-docker: command not found
exit status 1```

**Comment by clennan** [comment]
Hi, you need to install nvidia-docker on your ec2 instance. See here for more details on how to do that https://github.com/idealo/nvidia-docker-keras/blob/master/README.md#train-remote-on-gpu

I will add these steps to the README

**Comment by wmelton** [comment]
Ah! Super helpful. Thanks!
